#!/bin/bash
set -e

mysql -uroot -p"${MYSQL_ROOT_PASSWORD}" <<EOSQL
CREATE DATABASE IF NOT EXISTS QuickDeliveryDB CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS KeycloakDB CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS '${QUICKDELIVERY_DB_USERNAME}'@'%' IDENTIFIED BY '${QUICKDELIVERY_DB_PASSWORD}';
CREATE USER IF NOT EXISTS '${KEYCLOAK_DB_USERNAME}'@'%' IDENTIFIED BY '${KEYCLOAK_DB_PASSWORD}';

GRANT ALL PRIVILEGES ON QuickDeliveryDB.* TO '${QUICKDELIVERY_DB_USERNAME}'@'%';
GRANT ALL PRIVILEGES ON KeycloakDB.* TO '${KEYCLOAK_DB_USERNAME}'@'%';

FLUSH PRIVILEGES;
EOSQL

