server.port=8080
spring.application.name=DISCOVERY-SEREVER

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
#spring.security.basic.enabled=true
#spring.security.userDTO.name=admin
#spring.security.userDTO.password=admin

logging.level.com.netflix.eureka=OFF
logging.level.com.netflix.discovery=OFF

eureka.server.renewal-percent-threshold=0.85
eureka.server.renewal-threshold=10

eureka.server.wait-time-in-ms-when-sync-empty=0
eureka.server.response-cache-update-interval-ms=5000