import { required, email, maxLength } from '@vuelidate/validations';

export const validations = {
    package_: {
            id: {},
            version: {},
            creationDate: {},
            height: { required },
            width: { required },
            depth: { required },
            weight: { required },
            pictureURL: {},
            status: {},
            deliveryPrice: {},
            senderID: {},
            packageReservations: [],
            addresses: [
            {
            firstName: { required },
            lastName: { required },
            line1: { required },
            line2: {},
            town: { required },
            zipCode: { required },
            country: { required },
            email: { required },
            phone: { required },
            type: {},
            latitude: {},
            longitude: {},
          },
          {
            firstName: { required },
            lastName: { required },
            line1: { required },
            line2: {},
            town: { required },
            zipCode: { required },
            country: { required },
            email: { required, email },
            phone: { required, maxLength: maxLength(10) },
            type: {},
            latitude: {},
            longitude: {},
          }],
          lastPositionLatitude: {},
          lastPositionLongitude: {},
    },
};