package com.quickdelivery.abstarct.parameters;

public enum COURIER_PENALTY_TYPE {
    ROUTE_CANCELLED_BEFORE_START,
    ROUTE_CANCELLED_AFTER_START,
    ROUTE_NOT_STARTED_DEADLINE,
    ROUTE_PACKAGE_CANCELLED,
    ROUTE_STARTED_NO_PROGRESS,
    ROUTE_STARTED_WITHOUT_PENDING_STOP,
    STOP_VALIDATION_OUT_OF_RANGE
}
