package com.quickdelivery.abstarct.parameters;

public enum EMAIL_TYPE {
    PACKAGE_CREATION("PACKAGE_CREATION"),
    PACKAGE_RESERVATION_SENDER("PACKAGE_RESERVATION_SENDER"),
    PACKAGE_PICKUP_SENDER("PACKAGE_PICKUP_SENDER"),
    PACKAGE_PICKUP_DELIVERY("PACKAGE_PICKUP_DELIVERY"),
    PACKAGE_PICKUP_RECEIVER("PACKAGE_PICKUP_RECEIVER"),
    PACKAGE_DELIVERY_SENDER("PACKAGE_DELIVERY_SENDER"),
    PACKAGE_DELIVERY_RECEIVER("PACKAGE_DELIVERY_RECEIVER"),
    PACKAGE_RESERVATION_DELIVERY("PACKAGE_RESERVATION_DELIVERY");
    private String type;

    EMAIL_TYPE(String type){
        this.type = type;
    }
}
