package com.quickdelivery.abstarct.parameters;

public enum NOTIFICATION_EVENT_TYPE {
    PACKAGE_NEARBY,
    PACKAGE_CREATED,
    PACKAGE_RESERVED,
    PACKAGE_RESERVATION_OTP,
    PACKAGE_COURIER_ARRIVED_FOR_PICKUP,
    PACKAGE_PICKUP_STOP_ARRIVAL,
    PACKAGE_DELIVERY_STOP_ARRIVAL,
    PACKAGE_PICKED_UP,
    PACKAGE_PICKUP_SUCCESS,
    PACKAGE_DELIVERY_SUCCESS,
    PACKAGE_DELIVERED,
    PACKAGE_PAYMENT_CONFIRMED
}
