package com.quickdelivery.abstarct.parameters;

public enum DOCUMENT_TYPE {
    DRIVER_LICENCE("DRIVER_LICENCE"),
    PACKAGE_PICTURE("PACKAGE_PICTURE"),
    PACKAGE_INVOICE("PACKAGE_INVOICE"),
    VEHICLE_GRY_CARD("VEHICLE_GRY_CARD"),
    VEHICLE_INSURANCE_CARD("VEHICLE_INSURANCE_CARD"),
    USER_ID("USER_ID"),
    USER_COMPANY_EXTRACT("USER_COMPANY_EXTRACT"),
    USER_COMPANY_INSURANCE("USER_COMPANY_INSURANCE"),
    PACKAGE_QR("PACKAGE_QR"),
    PACKAGE_PDF_LABEL("PACKAGE_PDF_LABEL");
    private String addressType;

    DOCUMENT_TYPE(String addressType){
        this.addressType = addressType;
    }
}
