spring.application.name=Users_Service
spring.config.import=optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://config-server:8889}
spring.cloud.config.username=${CONFIG_SERVER_USERNAME:configuser}
spring.cloud.config.password=${CONFIG_SERVER_PASSWORD:configpass}
quickdelivery.ocr.textract.enabled=${QUICKDELIVERY_OCR_TEXTRACT_ENABLED:false}
quickdelivery.ocr.textract.region=${QUICKDELIVERY_OCR_TEXTRACT_REGION:eu-west-3}
