spring.application.name=CONFIGURATIONS-SERVER

server.port=8081

spring.cloud.config.server.git.uri=file:///${userDTO.home}/Documents/WorkSpace/Projects/DEV_WorkSpace/config
#spring.cloud.config.server.native.searchLocations=file:C:/Users/imess/Documents/WorkSpace/Projects/DEV_WorkSpace/config
#spring.cloud.config.server.bootstrap=true
eureka.client.serviceUrl.defaultZone=http://admin:admin@localhost:8080/eureka/
eureka.instance.prefer-ip-address=true
eureka.client.initial-instance-info-replication-interval-seconds=5
eureka.client.registry-fetch-interval-seconds=5
eureka.instance.lease-expiration-duration-in-seconds=5
eureka.instance.lease-renewal-interval-in-seconds=5

security.userDTO.name=SYSTEM
security.userDTO.password=SYSTEM
security.userDTO.role=SYSTEM
