spring.application.name=CONFIGURATIONS-SERVER

server.port=8889

spring.cloud.config.server.git.uri=file:///${user.home}/Documents/WorkSpace/Projects/DEV_WorkSpace/config
#spring.cloud.config.server.native.searchLocations=file:C:/Users/imess/Documents/WorkSpace/Projects/DEV_WorkSpace/config
#spring.cloud.config.server.bootstrap=true
eureka.client.serviceUrl.defaultZone=http://admin:admin@localhost:8080/eureka/
eureka.instance.prefer-ip-address=true
eureka.client.initial-instance-info-replication-interval-seconds=5
eureka.client.registry-fetch-interval-seconds=5
eureka.instance.lease-expiration-duration-in-seconds=5
eureka.instance.lease-renewal-interval-in-seconds=5

spring.security.user.name=${CONFIG_SERVER_USERNAME:configuser}
spring.security.user.password=${CONFIG_SERVER_PASSWORD:configpass}
spring.security.user.roles=CONFIG_SERVER

management.endpoints.web.exposure.include=health,info
