spring:
  config:
    import: optional:configserver:http://localhost:8889
  application:
    name: APIGatewayApplication
  cloud:
    config:
      username: ${CONFIG_SERVER_USERNAME:configuser}
      password: ${CONFIG_SERVER_PASSWORD:configpass}

management:
  endpoints:
    web:
      exposure:
        include: health,info
