spring.application.name=Package_Service
spring.config.import=optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://config-server:8889}
spring.cloud.config.username=${CONFIG_SERVER_USERNAME:configuser}
spring.cloud.config.password=${CONFIG_SERVER_PASSWORD:configpass}
management.endpoints.web.exposure.include=${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:health,info,metrics,prometheus}
management.endpoint.health.show-details=${MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS:when_authorized}
management.metrics.tags.application=${spring.application.name}
