spring.application.name=Package_Service
spring.config.import=optional:configserver:http://localhost:8889
spring.cloud.config.username=${CONFIG_SERVER_USERNAME:configuser}
spring.cloud.config.password=${CONFIG_SERVER_PASSWORD:configpass}
