server.port = 8082
spring.application.name=Package_Service

#spring.neo4j.uri=bolt://localhost:7687
#spring.neo4j.username=QuickDelivery_DBMS
#spring.neo4j.password=QuickDelivery_DBMS123

springfox.documentation.swagger-ui.enabled=true

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.datasource.url=jdbc:mysql://localhost:3306/QuickDeliveryDB
spring.datasource.username=QuickDelivery
spring.datasource.password=QuickDelivery123@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=false

logging.level.root=INFO
logging.level.com.quickdelivery=DEBUG

spring.cache.type=ehcache
spring.cache.jcache.config=classpath:ehcache.xml

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

mapquest.geocode.url.part1=https://www.mapquestapi.com/geocoding/v1/address?key=
mapquest.geocode.url.part2=&location=
mapquest.key=Avwlolrm3mgAMmWGuxRcSE7wM2LDHyMQ

googlemapsapi.key=AIzaSyC1JZHQfC9EUWUFKeHEBFnOMlZOUESxqog
#AIzaSyCBZNoGNPCcqSsTYTlOUhkXLhb47HqF9mM

package.services.getbyid.url=http://192.168.1.91:8082/packages/v1/package?id=
package.services.qrcode.file.location=C:\\QRs\\QR

application.otp.secret=QuickDelivery2023@
application.otp.counter=142536987

packages.docs.directory=${user.home}\\Documents\\QuickDelivery\\Packages\\