server:
  port: 18084

spring:
  config:
    import: optional:configserver:http://localhost:8889
  application:
    name: oauth-authorization-server
  cloud:
    config:
      username: ${CONFIG_SERVER_USERNAME:configuser}
      password: ${CONFIG_SERVER_PASSWORD:configpass}
