server:
  port: 18084

spring:
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://172.26.4.12:8889}
  application:
    name: oauth-authorization-server
  cloud:
    config:
      username: ${CONFIG_SERVER_USERNAME:configuser}
      password: ${CONFIG_SERVER_PASSWORD:configpass}
  jpa:
    open-in-view: false
